Prem redux
jim-is-me/Route-gaurd pull request #7
Opened 2023-01-29 08:56 UTC by jim-is-me

2023-01-29 08:57 UTC, jim-is-me commented
error: failed to push some refs to 'https://github.com/jim-is-me/Route-gaurd.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

2023-01-31 03:39 UTC, CodeNinja47 commented
It is a good practice to move all API calls into Redux. Trigger the API calls using actions from inside the `HomeWithRedux.js` component.

2023-01-31 03:43 UTC, CodeNinja47 requested changes

2023-01-31 03:43 UTC, CodeNinja47 commented on src/routegaurded_pages/HomeWithRedux.js
> +            const result = await axios.put(`http://localhost:8000/todos/${todo._id}`,{
Move this APi call into redux

2023-01-31 03:43 UTC, CodeNinja47 commented on src/routegaurded_pages/HomeWithRedux.js
> +            const result = await axios.post(`http://localhost:8000/todos/`,{
Move this APi call into redux

2023-01-31 03:43 UTC, CodeNinja47 commented on src/routegaurded_pages/HomeWithRedux.js
> +                console.log(resp)
Pass a callback function to the redux action. Trigger the callback function once the API call end. Ask me if you don't understand how

2023-01-31 03:43 UTC, CodeNinja47 commented on src/slices/appSlice.js
> +
Write 2 more actions here to `addTodo` and `updateTodo` which will call the respective APIs.

2023-02-08 09:16 UTC, merged